baseURL = "https://www.faintmarkdesign.com/"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "faint mark design"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.footer]]
URL = "tools"
name = "tools"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "tools"
name = "tools"
weight = 2
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "&copy; 2020 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"
description = "Inviting design for everyday use"
google_tag_manager = ""
home = "Home"
logo = "images/logo.svg"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Inviting design for everyday use"
[params.cookies]
enable = true
expire_days = 2
[params.cta]
description = "Sign up for unobtrusive updates on my latest designs. "
enable = true
image = "images/hugo-muscot.svg"
title = "Keep in touch"
[params.cta.button]
enable = true
label = "Yes, please!"
link = "#"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/faintmarkdesign/?hl=en"
